name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Build Backend
      working-directory: ./backend
      run: |
        npm ci
        npx prisma generate
        npm run build

    - name: Build Frontend
      working-directory: ./frontend
      run: |
        npm ci
        npm run build
